### ISSUE TITLE
Derniers ajouts pas bon !?

### ISSUE THREAD

**Issue by manland** [julien-lafont/Divx-Manager#1]
![S lection_002](https://f.cloud.github.com/assets/1492516/20630/dc3b332a-495d-11e2-8ebf-6bc76cae9edf.png)

Les derniers ajouts ne sont pas exactement les derniers ajouts !??

**Comment by julien-lafont** [comment]
Le bloc "dernier ajout" : 
- et transverse à tous les dossiers
- tient compte des dates des fichiers (et non des dossiers les contenant)

Du coup ça devrait être corret non ?

**Comment by manland** [comment]
Ba justement, pourquoi dans derniers ajouts y a "mis fits S4" au lieu de "Homeland s02" ?
